---
- name: Test that image server VM is ready
  hosts: k3s
  gather_facts: false
  tasks:
    - name: Wait for VM
      ansible.builtin.wait_for_connection:
        timeout: 60

- name: Install k3s
  hosts: k3s
  become: true
  gather_facts: true
  roles:
    - role: provision
    - role: k3s

- name: Install Calico and Metallb
  hosts: leader
  become: true
  roles:
    - role: calico
    - role: metallb
      vars:
        metallb_api_server_pool_name: api-server
        metallb_ingress_pool_name: ingress
        metallb_addresses:
          - name: "{{ metallb_api_server_pool_name }}"
            ip: "{{ cluster_api_vip }}"
          - name: "{{ metallb_ingress_pool_name }}"
            ip: "{{ cluster_ingress_vip }}"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: OpenISCSI install
  hosts: k3s
  become: true
  roles:
    - role: openiscsi

- name: Fetch kubeconfig
  hosts: leader
  gather_facts: false
  become: true
  tasks:
    - name: Fetch kubeconfig
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ kubeconfig_path }}"
        flat: true
