---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-diff
      - id: terraform_validate
        args:
          - --tf-init-args=-upgrade
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v26.4.0
    hooks:
      - id: ansible-lint
        args:
          - --exclude=.github
  - repo: https://github.com/crate-ci/typos
    rev: v1.46.0
    hooks:
      - id: typos
        args:
          - --force-exclude
          - --hidden
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
        args:
          - --disable=MD013
          - --disable=MD031
          - --disable=MD033
          - --dot
          - --fix
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: forbid-tabs
        exclude: \.tsv$
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.3
    hooks:
      - id: prettier
        args:
          - --prose-wrap=always
          - --quote-props=as-needed
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --enforce-all
          - --maxkb=2000
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        exclude: \.j2$
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.2
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args:
          - --external-sources
          - --shell=bash
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.22.0
    hooks:
      - id: terraform-docs-go
        args:
          - markdown
          - --output-file
          - README.md
          - modules/k3s-cluster
      - id: terraform-docs-go
        args:
          - markdown
          - --output-file
          - README.md
          - modules/k3s-cluster/provision
      - id: terraform-docs-go
        args:
          - markdown
          - --output-file
          - README.md
          - modules/kairos-k3s-cluster
      - id: terraform-docs-go
        args:
          - markdown
          - --output-file
          - README.md
          - modules/virtual-machine
      - id: terraform-docs-go
        args:
          - markdown
          - --output-file
          - README.md
          - modules/kubeconfig
      - id: terraform-docs-go
        args:
          - markdown
          - --output-file
          - README.md
          - modules/vault-k8s-config
