---
- name: Get k3s installed version
  ansible.builtin.command: k3s --version
  register: k3s_version_output
  changed_when: false
  ignore_errors: true

- name: Set k3s installed version
  when: k3s_version_output.rc == 0
  ansible.builtin.set_fact:
    installed_k3s_version:
      "{{ k3s_version_output.stdout_lines[0].split(' ')[2] }}"

- name: Download artifact only if needed
  when:
    k3s_version_output.rc != 0 or installed_k3s_version is version(k3s_version,
    '<')
  block:
    - name: Download K3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io/
        timeout: 120
        dest: /usr/local/bin/k3s-install.sh
        owner: root
        group: root
        mode: "0755"

    - name: Download K3s binary
      ansible.builtin.command:
        cmd: >-
          /usr/local/bin/k3s-install.sh {{ k3s_role }} {{ k3s_install_args |
          default('') }}
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
        K3S_TOKEN: "{{ node_token }}"
      changed_when: true

- name: Configure private registries
  ansible.builtin.template:
    src: registries.yaml.j2
    dest: /etc/rancher/k3s/registries.yaml
    mode: "0600"
  when: private_registries | from_yaml | length > 0
