---
- name: Install git
  ansible.builtin.package:
    name: git
    state: present

- name: Install python3-pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install python kubernetes client
  ansible.builtin.pip:
    name: kubernetes
    state: present
